#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/../../setup-vars
source $thisDirectory/../../build-vars

echo "Adding Dashboard"
# helm install stable/kubernetes-dashboard --name "dashboard"
kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml
echo "Done :-)"
