#!/bin/bash

# POD_NAME=$(kubectl get pods -n default -l "app=kubernetes-dashboard,release=dashboard" -o jsonpath="{.items[0].metadata.name}")
# echo "http://127.0.0.1:9090/"
# kubectl -n default port-forward $POD_NAME 9090:9090
echo "http://localhost:8001/ui"
kubectl proxy

