#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/../../setup-vars
source $thisDirectory/../../build-vars

echo "Adding NGINX"

helm install nginx stable/nginx-ingress 

echo "Done :-)"
