#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/../../setup-vars
source $thisDirectory/../../build-vars

echo "Adding NGINX"

helm install stable/nginx-ingress --name "nginx"

echo "Done :-)"
