#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

echo "Adding InfluxDB, Heapster"

kubectl apply -f $thisDirectory/persistent-volume.yaml
kubectl apply -f $thisDirectory/persistent-volume-claim.yaml

# originally from https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/influxdb.yaml
# copied here to add persistent volume claim
kubectl apply -f $thisDirectory/influxdb.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/heapster.yaml

askYesNoQuestion "Do you want to also add grafana?"
if [ $? -eq 1 ]; then
  echo "Also adding Grafana"
  kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml
fi

echo "Done :-)"
