#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

if [ -e $AWS_ACCESS_KEY_ID ] ||
   [ -e $AWS_SECRET_ACCESS_KEY ] ||
   [ -e $DOMAIN ]; then
cat <<-EOF
Missing required argument or ENV variable:
  $(displayPresence AWS_ACCESS_KEY_ID)
  $(displayPresence AWS_SECRET_ACCESS_KEY)
  $(displayPresence DOMAIN)
EOF
  exit 1
fi

kops delete cluster --name $KUBE_CLUSTER_NAME --state=$KOPS_STATE_STORE

echo ""

askYesNoQuestion "Are you sure you want to delete the cluster? This is not reversible."
if [ $? -eq 1 ]; then
  echo "Really deleting the cluster now..."
  kops delete cluster --name $KUBE_CLUSTER_NAME --state=$KOPS_STATE_STORE --yes
else
  echo -e "Canceled";
fi
