#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

kops edit cluster $KUBE_CLUSTER_NAME --state=$KOPS_STATE_STORE
