#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

kops edit cluster kube-cluster.kube.indyaws.darye.com --state=$KOPS_STATE_STORE
