#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

kops edit ig nodes --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME
