#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../kops-user

SITE_NAME=$(echo $DOMAIN | sed -e 's/\.\w*$//g')
KUBE_HOSTED_ZONE="$DOMAIN"
KUBE_CLUSTER_NAME="kube-cluster.$KUBE_HOSTED_ZONE"
S3_BUCKET_NAME="kube-$SITE_NAME"
KOPS_STATE_STORE="s3://$S3_BUCKET_NAME"

kops edit ig nodes --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME
