#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../kops-user
source $thisDirectory/../utility

SITE_NAME=$(echo $DOMAIN | sed -e 's/\.\w*$//g')
KUBE_HOSTED_ZONE="$DOMAIN"
KUBE_CLUSTER_NAME="kube-cluster.$KUBE_HOSTED_ZONE"
S3_BUCKET_NAME="kube-$SITE_NAME"
KOPS_STATE_STORE="s3://$S3_BUCKET_NAME"

kops rolling-update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME

askYesNoQuestion "Are you sure you want to perform a rolling update on your cluster?"
if [ $? -eq 1 ]; then
  echo "Performing rolling update cluster"
  kops rolling-update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME --yes
fi
