#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

kops rolling-update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME

askYesNoQuestion "Are you sure you want to perform a rolling update on your cluster?"
if [ $? -eq 1 ]; then
  echo "Performing rolling update cluster"
  kops rolling-update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME --yes
fi
