#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"

source $thisDirectory/../utility
source $thisDirectory/../setup-vars
source $thisDirectory/../build-vars

kops update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME

askYesNoQuestion "Are you sure you want to update your cluster?"
if [ $? -eq 1 ]; then
  echo "Updating Cluster"
  kops update cluster --state=$KOPS_STATE_STORE --name=$KUBE_CLUSTER_NAME --yes
fi
