#!/bin/bash

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/../../setup-vars
source $thisDirectory/../../build-vars

helm install stable/ghost --name ghost
kubectl get svc --namespace default -w ghost-ghost
