#!/bin/bash

# requires
# - AWS_REGION
# - KUBE_CLUSTER_NAME
# - AUTO_SCALER_MIN
# - AUTO_SCALER_MAX

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/../../setup-vars
source $thisDirectory/../../build-vars

if [ -e $AUTO_SCALER_MIN ] ||
  [ -e $AUTO_SCALER_MAX ] ||
  [ -e $KUBE_CLUSTER_NAME ] ||
  [ -e $AWS_REGION ]; then
cat <<-EOF
Missing required argument or ENV variable:
  $(displayPresence AUTO_SCALER_MIN)
  $(displayPresence AUTO_SCALER_MAX)
  $(displayPresence AWS_REGION)
  $(displayPresence KUBE_CLUSTER_NAME)
EOF
  exit 1
fi

echo "Adding a Cluster Auto-Scaler"

autoscalerYaml=${thisDirectory}/../../output/cluster-autoscaler.yaml
envsubst \$KUBE_CLUSTER_NAME,\$AUTO_SCALER_MIN,\$AUTO_SCALER_MAX,\$AWS_REGION < $thisDirectory/cluster-autoscaler.yaml.tmpl > $autoscalerYaml

kubectl apply -f $autoscalerYaml;

echo "Done :-)"
