#!/bin/bash

# requires
# - DATADOG_API_KEY

thisDirectory="${BASH_SOURCE%/*}"
source $thisDirectory/../../utility
source $thisDirectory/setup-vars

if [ -e $DATADOG_API_KEY ]; then
cat <<-EOF
Missing required argument or ENV variable:
  $(displayPresence DATADOG_API_KEY)
EOF
  exit 1
fi

echo "Deleting DataDog"

datadogAgentYaml=${thisDirectory}/../../output/datadog-agent.yaml;
envsubst \$DATADOG_API_KEY < $thisDirectory/datadog-agent.yaml.tmpl > $datadogAgentYaml

kubectl delete -f $datadogAgentYaml

echo "Done :-)"
